const ATTENDANCE_THRESHOLD = 0.75;
const POINTS = {
  LIVE_CLASS_ATTENDANCE: 10,
  VOD_COMPLETION: 5,
  POLL_ANSWER: 2
};
const VOD_COMPLETION_THRESHOLD = 0.90;

module.exports = {
  ATTENDANCE_THRESHOLD,
  POINTS,
  VOD_COMPLETION_THRESHOLD
};
